version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - datadir:/var/lib/mysql
    env_file:
      - ./env/mariadb.env
  backend:
    image: node:latest
    volumes:
      - logs:/app/logs
      - /app/node_modules
    ports:
      - 80:80
    environment:
      - MARIADB_USERNAME=mike
      - MARIADB_PASSWORD=secret
  npm:
    build: ./dockerfiles/npm.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
volumes:
  datadir:
  logs:

  